### ISSUE TITLE
Modify Welcome Screen

### ISSUE THREAD

**Issue by dcipher00** [dcipher00/Frindi#2]
Welcome screen consists of 2 buttons
## Login & Register
Add Css to the buttons, Add Touchable Opacity
## Unify button size and style

**Comment by snowmanstark** [comment]
@dcipher00 Can I start working on this?

**Comment by dcipher00** [comment]
@snowmanstark sure go ahead

**Comment by dcipher00** [comment]
@snowmanstark you can use this image as the background

https://drive.google.com/open?id=1RKRp-3J_17MB9CKfM8WTts258HsQtwDr

or you may also find the image in assets folder as splash.png

**Comment by snowmanstark** [comment]
@dcipher00 okay, so I'll be using the same splash image path for the welcome screen.

**Comment by dcipher00** [comment]
@snowmanstark  yes you can, also for your reference you can check how it has been imported in Login Screen

**Comment by dcipher00** [comment]
@snowmanstark refer issue #12 for a similar detailed description regarding the buttons.
