### ISSUE TITLE
Add Profile Screen

### ISSUE THREAD

**Issue by dcipher00** [dcipher00/Frindi#29]
Add Profile screen to be navigated through App drawer with a back button in the center

**Comment by thesanjeevsharma** [comment]
Hello, I would like to take this issue.

**Comment by dcipher00** [comment]
sure go ahead

**Comment by dcipher00** [comment]
@thesanjeevsharma are you still working on this issue cause some contributors would like to take over in case you are struck somewhere.

**Comment by dcipher00** [comment]
@Sagarika00 you can go with this issue
