### ISSUE TITLE
Remove Navigation header from the welcome page

### ISSUE THREAD

**Issue by dcipher00** [dcipher00/Frindi#42]
Remove Navigation header from the welcome page which contains the title Frindi.

**Comment by techno-knight** [comment]
@dcipher00  Can I take it?

**Comment by dcipher00** [comment]
@prime417  sure, feel free to raise the PR

**Comment by dcipher00** [comment]
@prime417 thank you, i have merged your PR. Also from next time please use keywords to auto close the issue.
