### ISSUE TITLE
Add social sign in buttons

### ISSUE THREAD

**Issue by dcipher00** [dcipher00/Frindi#7]
Add social Sign in buttons on Login screen
## Twitter
Recommended to use icons from https://ionicons.com/
can import through **expo vector icons**

**Comment by snowmanstark** [comment]
@dcipher00 If this is not assigned to anyone, I'll start working on this after it is assigned to me.

**Comment by dcipher00** [comment]
@snowmanstark please one issue at a time. Once you are done with the 1st pr, you can proceed with this.

**Comment by snowmanstark** [comment]
I will be using icons from https://icons8.com since it has a far better and humongous library than https://ionicons.com/

**Comment by dcipher00** [comment]
@snowmanstark  sure recommendations are optional, you should always use the best

**Comment by Infabytes-gaurav** [comment]
Use https://material.io/resources/icons/?style=baseline instead of https://icons8.com/ as it'll be a tedious job of adding the image and then tweaking them around, which otherwise is automatically done after importing the material-icons package.
